version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

  deploy-to-heroku:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/strangeback.git main

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy-to-heroku:
          requires:
            - build-and-test
